// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://korhvkcrxyvnhrezwisi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtvcmh2a2NyeHl2bmhyZXp3aXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MjkxNzksImV4cCI6MjA2NDEwNTE3OX0.BlpiQ-urmpK-oDxGJqi87IRYxc7U-UdY7BB8MeGWCKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);